console.log("加载完成");
//配置当前整个项目所有模块的路径
require.config({
    paths:{
        jquery:"jquery-1.11.3",
        "jquery-cookie":"jquery.cookie",
        parabola:"parabola",
        "login":"login",
        "r_login":"r_login",
        "ajax":"ajax",
        //页面跳转
        "openNewHtml":"openNewHtml",
        
    },
    shim:{
        "jquery-cookie":['jquery'],
        "parabola":{
            exports:"_"
        }
    }
})
require(["login","r_login","ajax","openNewHtml"],function(login,r_login,ajax,openNewHtml){
    login.login();
    r_login.r_login();
    ajax.ajax();
    openNewHtml.openNewHtml();
})